# .forgejo/workflows/Test-Cross-Build.yaml
name: Кроссплатформенная проверка сборки приложения
on:
  workflow_dispatch: {}
jobs:
  Build-Linux:
    runs-on: ubuntu-24
    container:
      # https://hub.docker.com/r/ivangabriele/tauri
      image: 192.168.20.32/library/tauri:d12n22
      options: "--tty"
    env:
      CI_SERVER_URL: ${{ github.server_url }}
      CI_REPOSITORY: ${{ github.repository }}
      CI_JOB_TOKEN: ${{ secrets.FORGEJO_ACCESS_TOKEN }}
    steps:
      - name: Установка системных пакетов
        run: apt-get update && apt-get install -y libudev-dev libssl-dev xdg-utils git curl jq coreutils grep
      - name: Клонирование репозитория
        run: git clone --recursive "http://${CI_JOB_TOKEN}:x-oauth-basic@${CI_SERVER_URL#http://}/${CI_REPOSITORY}.git" .
      - name: Установка зависимостей
        run: npm ci
      - name: Сборка приложения
        run: npm run tauri build
      - name: Очистка
        run: rm -rf src-tauri/target node_modules

  Build-Windows:
    runs-on: ubuntu-24
    container:
      # https://hub.docker.com/r/ivangabriele/tauri
      image: 192.168.20.32/library/tauri:d12n22
      options: "--tty"
    env:
      CI_SERVER_URL: ${{ github.server_url }}
      CI_REPOSITORY: ${{ github.repository }}
      CI_JOB_TOKEN: ${{ secrets.FORGEJO_ACCESS_TOKEN }}
    steps:
      - name: Установка системных пакетов
        run: apt-get update && apt-get install -y libudev-dev libssl-dev mingw-w64 nsis git curl jq coreutils grep
      - name: Клонирование репозитория
        run: git clone --recursive "http://${CI_JOB_TOKEN}:x-oauth-basic@${CI_SERVER_URL#http://}/${CI_REPOSITORY}.git" .
      - name: Установка зависимостей
        run: npm ci
      - name: Установка цели для Rust
        run: rustup target add x86_64-pc-windows-gnu
      - name: Сборка приложения
        run: npm run tauri build -- --target x86_64-pc-windows-gnu
      - name: Очистка
        run: rm -rf src-tauri/target node_modules

  Build-MacOS:
    runs-on: ubuntu-24
    container:
      # https://hub.docker.com/r/joseluisq/rust-linux-darwin-builder
      image: 192.168.20.32/library/rust-linux-darwin-builder
      options: "--tty"
    env:
      CI_SERVER_URL: ${{ github.server_url }}
      CI_REPOSITORY: ${{ github.repository }}
      CI_JOB_TOKEN: ${{ secrets.FORGEJO_ACCESS_TOKEN }}
    steps:
      - name: Установка системных пакетов
        run: |
          apt-get update && apt-get install -y git curl jq coreutils grep
          curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
          apt-get install -y nodejs
      - name: Клонирование репозитория
        run: git clone --recursive "http://${CI_JOB_TOKEN}:x-oauth-basic@${CI_SERVER_URL#http://}/${CI_REPOSITORY}.git" .
      - name: Установка зависимостей
        run: npm ci
      - name: Сборка приложения (Intel x64)
        run: |
          export CC=o64-clang
          export CXX=o64-clang++
          npm run tauri build -- --target x86_64-apple-darwin
      - name: Сборка приложения (Apple Silicon ARM64)
        run: |
          export CC=oa64-clang
          export CXX=oa64-clang++
          npm run tauri build -- --target aarch64-apple-darwin
      - name: Очистка
        run: rm -rf src-tauri/target node_modules
